"""Real-simulator backend #2: PX4 SITL (MAVLink) + Gazebo (gz sim) + ROS 2,
bridged via MAVROS and ros_gz_bridge. This is a structural template, not a
bundled asset -- it requires:

  1. A sourced ROS 2 install (rclpy) plus mavros, ros_gz_bridge, cv_bridge.
  2. A running PX4 SITL instance (speaks MAVLink) paired with Gazebo via
     PX4's own gz integration (e.g. `PX4_SIM_MODEL=gz_x500_depth make px4_sitl gz_x500_depth`),
     loading a world generated by `ros_gazebo_bridge.world_gen` (see
     `launch/corridor_sim.launch.py`).
  3. MAVROS running and connected to PX4's MAVLink stream, plus
     ros_gz_bridge relaying the vehicle's camera/depth/odometry topics
     into ROS 2 (topic names configurable under `env.ros.*`).

It implements the same `BaseCorridorEnv` contract as `MockCorridorEnv`
and `AirSimCorridorEnv`, so `star_nav.training.train_ppo` does not need
to know which backend is in use -- only `configs/default.yaml`'s
`env.name` changes (set it to `gazebo_ros`).

Important difference from the other two backends: Gazebo cannot cheaply
regenerate hundreds of trunk models every episode, so `reset()` does NOT
re-randomize the corridor layout. The world is generated once ahead of
time (`python -m ros_gazebo_bridge.world_gen ...`) and `reset()` only
teleports the vehicle back to the start pose and re-arms/re-offboards it;
`scenario` is used purely to validate that the currently loaded world's
ground-truth layout tag matches what the caller expects. `weather` is
accepted for interface compatibility but is currently a no-op (Gazebo has
no direct equivalent of AirSim's weather API) -- see README.md.
"""
from __future__ import annotations

import os

import numpy as np

try:
    import rclpy
except ImportError as exc:  # pragma: no cover
    raise ImportError(
        "GazeboROSEnv requires a sourced ROS 2 install (rclpy) plus mavros, "
        "ros_gz_bridge, and a running PX4 SITL + Gazebo session. See "
        "ros_gazebo_bridge/README.md. Use env.name: mock in configs/default.yaml "
        "to run without any of this."
    ) from exc

from star_nav.envs.base_env import BaseCorridorEnv, EnvObservation, EnvStepResult, PrivilegedInfo

from .ros_bridge_node import ROSGazeboBridge
from .world_gen import load_world_layout


class GazeboROSEnv(BaseCorridorEnv):
    def __init__(self, cfg):
        self.cfg = cfg
        self._max_forward_speed = cfg.get("max_forward_speed", 2.5) if hasattr(cfg, "get") else getattr(
            cfg, "max_forward_speed", 2.5)
        self._max_yaw_rate = np.deg2rad(120.0)
        self.dt = 0.2
        self._hold_alt = 2.2          # corridor flight altitude (matches _takeoff target)
        self._alt_hold_gain = 0.8     # P-gain for the deploy altitude-hold (see step)
        # Yaw-lock: the corridor's forward axis is world +x and the vehicle spawns
        # facing it, so (like the Mock env, where forward stays +x) we hold heading
        # at 0 instead of letting the policy's yaw-rate spin the body frame off the
        # corridor -- a spun body frame turns the policy's "forward" v_x into a
        # sideways/backward world motion, which is a big part of the observed wander.
        self._yaw_lock = True
        self._yaw_lock_gain = 1.5
        self.max_steps = cfg.episode_max_steps
        self._t = 0
        self._prev_goal_dist = 0.0
        self._prev_omega = 0.0
        self._prev_v = np.zeros(3)

        ros_cfg = cfg.ros
        layout_path = ros_cfg.world_layout_json
        if not os.path.isabs(layout_path):
            repo_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
            layout_path = os.path.join(repo_root, layout_path)
        self._world = load_world_layout(layout_path)

        if not rclpy.ok():
            rclpy.init()
        self.node = ROSGazeboBridge(ros_cfg, node_name=getattr(ros_cfg, "node_name", "star_nav_bridge"))
        self.node.wait_until_ready()

    @property
    def max_forward_speed(self) -> float:
        return self._max_forward_speed

    def reset(self, scenario: str = "A", weather: str = "clear_day") -> EnvObservation:
        if self._world.scenario and self._world.scenario != scenario:
            raise ValueError(
                f"Requested scenario '{scenario}' but the currently loaded Gazebo world was "
                f"generated for scenario '{self._world.scenario}' (env.ros.world_layout_json="
                f"{self.cfg.ros.world_layout_json}). Generate/launch the matching world instead "
                f"of expecting reset() to re-randomize it -- see ros_gazebo_bridge/README.md."
            )
        # `weather` is accepted for BaseCorridorEnv interface compatibility only; see module docstring.

        self.node.disarm()
        self.node.arm_and_offboard()
        self._takeoff()
        self._t = 0
        self._prev_omega = 0.0
        self._prev_v = np.zeros(3, dtype=np.float32)
        self.node.wait_until_ready()

        obs, info = self._observe()
        self._prev_goal_dist = info.goal_distance
        return obs

    def _current_alt(self):
        """Latest ground-truth altitude (m), or None if no odom yet."""
        try:
            *_, gt_pose = self.node.get_latest()
            return float(gt_pose[2])
        except Exception:
            return None

    def _current_yaw(self):
        """Latest ground-truth yaw (rad, world frame), or None if no odom yet."""
        try:
            *_, gt = self.node.get_latest()   # [x,y,z, qx,qy,qz,qw]
            qx, qy, qz, qw = gt[3], gt[4], gt[5], gt[6]
            return float(np.arctan2(2 * (qw * qz + qx * qy), 1 - 2 * (qy * qy + qz * qz)))
        except Exception:
            return None

    def _takeoff(self, target_alt: float = 2.2, climb_speed: float = 1.0, timeout: float = 10.0):
        """Climb to corridor flight altitude before handing control to the policy.

        The Mock corridor the policy trains in has no vertical dynamics (it flies
        at a fixed height), so the policy never commands a takeoff; without this
        the armed vehicle just sits on the ground and every horizontal setpoint
        is fought by ground contact. Stream a body-frame climb until gt_odom
        altitude reaches the target (matches the 2.2 m capture-rig height, so the
        camera viewpoint is in-distribution for SACR/CAMR), then settle to hover.
        """
        import time as _time
        self._hold_alt = target_alt   # keep the step() altitude-hold consistent with takeoff
        t0 = _time.time()
        while _time.time() - t0 < timeout:
            z = self._current_alt()
            if z is not None and z >= target_alt - 0.15:
                break
            self.node.send_body_velocity_setpoint(0.0, 0.0, climb_speed, 0.0)
            self.node.spin_for(self.dt)
        for _ in range(3):  # settle at altitude before the policy takes over
            self.node.send_body_velocity_setpoint(0.0, 0.0, 0.0, 0.0)
            self.node.spin_for(self.dt)

    def step(self, action: np.ndarray) -> EnvStepResult:
        action = np.clip(np.asarray(action, dtype=np.float32), -1.0, 1.0)
        v_x, v_y, _v_z_unused, omega_n = action
        v_x = float(v_x * self._max_forward_speed)
        v_y = float(v_y * self._max_forward_speed)
        # The Mock corridor the policy trains in is 2-D: its step() unpacks v_z
        # but never applies it, so the policy gets zero gradient on action[2] and
        # emits untrained noise there (which, applied as a real climb, rockets the
        # vehicle to tens of metres). Ignore it and hold the corridor altitude
        # with a simple P-controller instead -- matching the fixed-height regime
        # the policy actually learned.
        z = self._current_alt()
        v_z = 0.0 if z is None else float(
            np.clip(self._alt_hold_gain * (self._hold_alt - z), -1.0, 1.0) * self._max_forward_speed)
        if self._yaw_lock:
            # Hold heading at +x (corridor forward): ignore the policy yaw-rate and
            # drive a P yaw-rate toward yaw=0, so body-forward stays corridor-forward.
            yaw = self._current_yaw()
            if yaw is None:
                omega = 0.0
            else:
                yaw_err = (-yaw + np.pi) % (2 * np.pi) - np.pi   # wrap to [-pi, pi], target 0
                omega = float(np.clip(self._yaw_lock_gain * yaw_err, -1.0, 1.0) * self._max_yaw_rate)
        else:
            omega = float(omega_n * self._max_yaw_rate)

        self.node.send_body_velocity_setpoint(v_x, v_y, v_z, omega)
        self.node.spin_for(self.dt)
        self._t += 1

        obs, info = self._observe()

        r_progress = (self._prev_goal_dist - info.goal_distance) / self._max_forward_speed
        d_omega = omega - self._prev_omega
        d_v = np.array([v_x, v_y, v_z], dtype=np.float32) - self._prev_v
        r_smooth = -abs(d_omega) - float(np.linalg.norm(d_v))
        r_alive = 0.01
        reward = 1.0 * r_progress + 0.05 * r_smooth + 0.01 * r_alive
        if info.collided:
            reward -= 5.0

        self._prev_goal_dist = info.goal_distance
        self._prev_omega = omega
        self._prev_v = np.array([v_x, v_y, v_z], dtype=np.float32)

        success = info.goal_distance < 1.5
        timeout = self._t >= self.max_steps
        done = bool(success or info.collided or timeout)

        return EnvStepResult(obs=obs, reward=float(reward), done=done, success=success, info=info)

    def _observe(self) -> "tuple[EnvObservation, PrivilegedInfo]":
        rgb, depth, seg, imu, local_pose, gt_pose = self.node.get_latest()

        # The gz depth camera returns +inf (and occasionally NaN) for pixels
        # with no return inside its far clip -- i.e. sky and anything past
        # DEPTH_FAR_FILL m. A naive region .mean() then yields inf/NaN, which
        # poisons theta_corr_gt's depth thirds and SACR's L_geom target. Treat
        # a no-return as "free/far" (the physically correct corridor
        # free-distance reading) by clamping non-finite depth to the far cap
        # before pooling. DEPTH_FAR_FILL matches the fpv5/pavo_femto depth
        # camera's <clip><far> (DEPTH_MAX_RANGE_M) in *_gen.py -- keep in sync.
        DEPTH_FAR_FILL = 20.0
        depth = np.nan_to_num(depth, nan=DEPTH_FAR_FILL, posinf=DEPTH_FAR_FILL, neginf=0.0)
        depth = np.clip(depth, 0.0, DEPTH_FAR_FILL)

        w = depth.shape[1]
        d_left = float(depth[:, : w // 3].mean())
        d_center = float(depth[:, w // 3: 2 * w // 3].mean())
        d_right = float(depth[:, 2 * w // 3:].mean())

        gt_xy = gt_pose[:2]
        collided = bool(np.any(np.linalg.norm(self._world.tree_xy - gt_xy[None, :], axis=1)
                                < self._world.trunk_radius + 0.15))
        lateral_dev = float(gt_xy[1] - self._world.corridor_center_y)
        off_lane = bool(abs(lateral_dev) > 4.0)
        goal_distance = float(np.linalg.norm(gt_xy - self._world.goal_xy))

        # phi = corridor-heading error. The corridor's forward axis is world
        # +x (same layout algorithm as MockCorridorEnv._generate_world /
        # world_gen.py's build_corridor_world), so phi is just the vehicle's
        # own world yaw, extracted from the ground-truth odometry quaternion
        # (gt_pose[3:7] = qx, qy, qz, qw). Matches MockCorridorEnv's
        # definition exactly (theta_corr_gt[0] == self._heading there).
        qx, qy, qz, qw = gt_pose[3], gt_pose[4], gt_pose[5], gt_pose[6]
        phi = float(np.arctan2(2.0 * (qw * qz + qx * qy), 1.0 - 2.0 * (qy * qy + qz * qz)))

        obs = EnvObservation(rgb=rgb, pose=local_pose, imu=imu)
        info = PrivilegedInfo(
            seg_mask=seg,
            depth=depth,
            theta_corr_gt=np.array([phi, d_left, d_right, d_center], dtype=np.float32),
            d_left=d_left,
            d_right=d_right,
            goal_distance=goal_distance,
            collided=collided,
            off_lane=off_lane,
            lateral_deviation=lateral_dev,
        )
        return obs, info

    def close(self) -> None:
        self.node.disarm()
        self.node.shutdown()  # stop the background executor thread first
        self.node.destroy_node()
