"""Procedural Gazebo model generator for a generic 5-inch FPV freestyle
quad -- a second vehicle variant alongside the real-hardware
``pavo_femto`` model (``pavo_femto_gen.py``), added so STAR-Nav can be
evaluated against a more conventional open-frame racing/freestyle
quadcopter (225mm-class true-X) instead of only the tiny 75mm whoop.

Unlike ``pavo_femto`` (which mirrors one specific, exactly-specified
real drone), this model synthesizes a *representative* mainstream 5"
build from Oscar Liang's "Best 5 Inch FPV Drone And Its Components"
buying guide (2025-04-01, user-provided 2026-07-05), which lists several
interchangeable options per part rather than one fixed kit. Choices made
here, and why:

    Frame:    GEPRC Vapor X5 "true X" layout (225mm-class wheelbase) --
              picked over the D5 "wide X" variant because true-X is the
              more generic/standard geometry for freestyle (D5's wide-X
              is a deliberate cinematic-specific tradeoff, keeping props
              out of frame at the cost of standard proportions).
    Motor:    iFlight Xing2 2207, ~1900KV (the guide's "tried and
              tested" pick) -- representative of the 2207-size class
              common to every motor option listed (T-Motor Velox
              V2207.5, RCinPower Wasp Major, EMAX ECO II 2207 are all
              the same stator-size class with similar KV range).
    Propeller: 5.1-inch 3-blade (HQ 5.1x2.5x3 / Gemfan Hurricane
              5146-3 class) -- the guide's props are all ~5.1in
              3-blade, differing mainly in pitch/application (racing vs
              cinematic), not diameter.
    Camera/VTX: DJI O4 Pro air unit, as explicitly named for the guide's
              top frame pick (GEPRC Vapor D5/X5).
    FC/ESC:   Not modeled physically (irrelevant to Gazebo rigid-body
              sim) -- SpeedyBee F405 Mini stack (the guide's value pick)
              is only used to sanity-check the overall mass budget.

As with ``pavo_femto_gen.py``: no mesh tooling is available in this
environment, so the frame is built entirely from SDF primitives. This is
an open (non-ducted) true-X frame, unlike the whoop's fused duct rings --
structurally the two models share little beyond both being generated by
the same technique. Physical constants not pinned down by the buying
guide (motor thrust curve, inertia, camera tilt) are engineering
estimates for a typical 5" freestyle quad, not measured bench data.
"""
from __future__ import annotations

import argparse
import math
import os

# ---------------------------------------------------------------------------
# Dimensions (representative 5" true-X freestyle quad)
# ---------------------------------------------------------------------------
WHEELBASE_M = 0.225  # motor-to-motor diagonal, typical true-X 5" freestyle frame (e.g. GEPRC Vapor X5 class)
ARM_OFFSET_M = WHEELBASE_M / (2 * math.sqrt(2))  # per-axis motor offset, ~0.0796 m

ARM_WIDTH_M = 0.010
ARM_THICKNESS_M = 0.005
ARM_LENGTH_MARGIN = 1.08  # arms extend slightly past the motor center visually

PROP_DIAMETER_M = 0.130  # "5-inch" class (~5.1in / 130mm), e.g. HQ 5.1x2.5x3 / Gemfan Hurricane 5146-3
PROP_RADIUS_M = PROP_DIAMETER_M / 2.0
PROP_BLADE_COUNT = 3
PROP_BLADE_WIDTH_M = 0.014
PROP_BLADE_THICKNESS_M = 0.0018

MOTOR_RADIUS_M = 0.0135  # "2207" class (iFlight Xing2 2207 / T-Motor Velox V2207.5 / EMAX ECO II 2207), ~27mm diameter
MOTOR_HEIGHT_M = 0.030

# Center stack: top + bottom carbon plates sandwiching the arms, standard
# "unibody" 5" frame construction, holding the FC/ESC stack between them.
PLATE_SIZE_M = (0.062, 0.062, 0.003)
STACK_HEIGHT_M = 0.032  # bottom plate to top plate
STANDOFF_RADIUS_M = 0.0025

# Front camera pod (DJI O4 Pro air unit -- larger than the O4 Lite used on
# pavo_femto). Tilt defaults to a typical freestyle up-tilt (nose up helps
# forward visibility at speed); override via --camera-tilt-deg (positive =
# nose-down, matching pavo_femto_gen.py's convention) if a level or
# corridor-optimized angle is wanted instead.
CAMERA_POD_SIZE_M = (0.028, 0.028, 0.026)
DEFAULT_CAMERA_TILT_DEG = -20.0

ANTENNA_RADIUS_M = 0.002
ANTENNA_LENGTH_M = 0.05

# ---------------------------------------------------------------------------
# Mass budget: representative 5" freestyle BNF dry weight (no battery, same
# battery-excluded convention as pavo_femto_gen.py).
# ---------------------------------------------------------------------------
TOTAL_MASS_KG = 0.300
ROTOR_MASS_KG = 0.032  # per motor+prop, 2207-class motor + 5" tri-blade prop
BASE_MASS_KG = TOTAL_MASS_KG - 4 * ROTOR_MASS_KG  # frame + FC/ESC stack + camera + VTX + antenna + wiring

# Motor-model constants for gz-sim-multicopter-motor-model-system.
# Engineering estimate for an iFlight-Xing2-2207-class motor (~1900KV) +
# 5.1in 3-blade prop on 6S: ~700 gf (~7N) max static thrust per motor is a
# fairly conservative/representative value for this class (racing-tuned
# builds can exceed this; freestyle setups are commonly in this range),
# giving an aggressive but plausible freestyle-class thrust-to-weight
# ratio around 9-10 at the 300g dry weight used here.
MOTOR_MAX_ROT_VELOCITY = 3300.0  # rad/s, ~31500 RPM under load -- plausible for 1900KV on 6S with a 5" prop
MOTOR_MAX_THRUST_N = 7.0
MOTOR_CONSTANT = MOTOR_MAX_THRUST_N / (MOTOR_MAX_ROT_VELOCITY ** 2)
MOTOR_MOMENT_CONSTANT = 0.025
MOTOR_TIME_CONSTANT_UP = 0.01
MOTOR_TIME_CONSTANT_DOWN = 0.02
# Scaled down from x500's 1345 (0.33m) prop coefficients by (prop-diameter ratio)^2.
ROTOR_DRAG_COEFFICIENT = 8.06428e-05 * (PROP_DIAMETER_M / 0.33) ** 2
ROLLING_MOMENT_COEFFICIENT = 1e-06 * (PROP_DIAMETER_M / 0.33) ** 2

# Camera: 640x480 @ 30 FPS per the paper's UAV/Simulation Configuration
# table. Horizontal FOV kept at 90 deg for consistency with
# MockCorridorEnv and pavo_femto_gen.py, NOT because that matches a real
# DJI O4 Pro's actual (much wider) FOV -- this is a deliberate
# cross-backend consistency choice, not a hardware replication.
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
CAMERA_FPS = 30
CAMERA_HFOV_RAD = math.radians(90.0)
DEPTH_HFOV_RAD = math.radians(90.0)
DEPTH_MAX_RANGE_M = 20.0


def _pose(x: float, y: float, z: float, roll: float = 0.0, pitch: float = 0.0, yaw: float = 0.0) -> str:
    return f"{x:.5f} {y:.5f} {z:.5f} {roll:.5f} {pitch:.5f} {yaw:.5f}"


def _arm_visual(name: str, motor_x: float, motor_y: float, z: float) -> str:
    length = math.hypot(motor_x, motor_y) * ARM_LENGTH_MARGIN
    angle = math.atan2(motor_y, motor_x)
    mid_x = (motor_x / ARM_LENGTH_MARGIN) / 2.0 * ARM_LENGTH_MARGIN
    mid_y = (motor_y / ARM_LENGTH_MARGIN) / 2.0 * ARM_LENGTH_MARGIN
    return f"""
      <visual name="{name}">
        <pose>{_pose(mid_x, mid_y, z, 0, 0, angle)}</pose>
        <geometry>
          <box><size>{length:.5f} {ARM_WIDTH_M:.5f} {ARM_THICKNESS_M:.5f}</size></box>
        </geometry>
        <material><ambient>0.02 0.02 0.02 1</ambient><diffuse>0.05 0.05 0.05 1</diffuse></material>
      </visual>
      <collision name="{name}_collision">
        <pose>{_pose(mid_x, mid_y, z, 0, 0, angle)}</pose>
        <geometry>
          <box><size>{length:.5f} {ARM_WIDTH_M:.5f} {ARM_THICKNESS_M:.5f}</size></box>
        </geometry>
      </collision>"""


def _prop_blades(link_name: str) -> str:
    parts = []
    for i in range(PROP_BLADE_COUNT):
        angle = 2 * math.pi * i / PROP_BLADE_COUNT
        cx = (PROP_RADIUS_M / 2.0) * math.cos(angle)
        cy = (PROP_RADIUS_M / 2.0) * math.sin(angle)
        parts.append(f"""
      <visual name="{link_name}_blade{i}">
        <pose>{_pose(cx, cy, 0, 0, 0, angle)}</pose>
        <geometry>
          <box><size>{PROP_RADIUS_M:.5f} {PROP_BLADE_WIDTH_M:.5f} {PROP_BLADE_THICKNESS_M:.5f}</size></box>
        </geometry>
        <material><ambient>0.05 0.05 0.05 1</ambient><diffuse>0.08 0.08 0.08 1</diffuse></material>
      </visual>""")
    return "".join(parts)


def _rotor_link(index: int, cx: float, cy: float, z: float, turning_direction: str) -> str:
    ixx_iyy = ROTOR_MASS_KG * PROP_DIAMETER_M ** 2 / 12.0
    izz = ROTOR_MASS_KG * (PROP_RADIUS_M ** 2) / 2.0
    return f"""
    <link name="rotor_{index}">
      <gravity>true</gravity>
      <self_collide>false</self_collide>
      <velocity_decay/>
      <pose>{_pose(cx, cy, z)}</pose>
      <inertial>
        <mass>{ROTOR_MASS_KG:.6f}</mass>
        <inertia>
          <ixx>{ixx_iyy:.3e}</ixx>
          <iyy>{ixx_iyy:.3e}</iyy>
          <izz>{izz:.3e}</izz>
        </inertia>
      </inertial>
      <visual name="rotor_{index}_motor">
        <pose>0 0 {-MOTOR_HEIGHT_M / 2:.5f} 0 0 0</pose>
        <geometry>
          <cylinder><radius>{MOTOR_RADIUS_M:.5f}</radius><length>{MOTOR_HEIGHT_M:.5f}</length></cylinder>
        </geometry>
        <material>
          <ambient>0.15 0.15 0.15 1</ambient>
          <diffuse>0.3 0.3 0.3 1</diffuse>
          <specular>0.6 0.6 0.6 1</specular>
        </material>
      </visual>
      {_prop_blades(f"rotor_{index}")}
      <collision name="rotor_{index}_collision">
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <box><size>{PROP_DIAMETER_M:.5f} {PROP_BLADE_WIDTH_M * 2:.5f} {PROP_BLADE_THICKNESS_M * 2:.5f}</size></box>
        </geometry>
      </collision>
    </link>
    <joint name="rotor_{index}_joint" type="revolute">
      <parent>base_link</parent>
      <child>rotor_{index}</child>
      <axis>
        <xyz>0 0 1</xyz>
        <limit><lower>-1e+16</lower><upper>1e+16</upper></limit>
        <dynamics><spring_reference>0</spring_reference><spring_stiffness>0</spring_stiffness></dynamics>
      </axis>
    </joint>"""


def _motor_plugin(index: int, turning_direction: str) -> str:
    return f"""
    <plugin filename="gz-sim-multicopter-motor-model-system" name="gz::sim::systems::MulticopterMotorModel">
      <jointName>rotor_{index}_joint</jointName>
      <linkName>rotor_{index}</linkName>
      <turningDirection>{turning_direction}</turningDirection>
      <timeConstantUp>{MOTOR_TIME_CONSTANT_UP}</timeConstantUp>
      <timeConstantDown>{MOTOR_TIME_CONSTANT_DOWN}</timeConstantDown>
      <maxRotVelocity>{MOTOR_MAX_ROT_VELOCITY}</maxRotVelocity>
      <motorConstant>{MOTOR_CONSTANT:.6e}</motorConstant>
      <momentConstant>{MOTOR_MOMENT_CONSTANT}</momentConstant>
      <commandSubTopic>command/motor_speed</commandSubTopic>
      <motorNumber>{index}</motorNumber>
      <rotorDragCoefficient>{ROTOR_DRAG_COEFFICIENT:.3e}</rotorDragCoefficient>
      <rollingMomentCoefficient>{ROLLING_MOMENT_COEFFICIENT:.3e}</rollingMomentCoefficient>
      <rotorVelocitySlowdownSim>10</rotorVelocitySlowdownSim>
      <motorType>velocity</motorType>
    </plugin>"""


def build_model_sdf(camera_tilt_deg: float = DEFAULT_CAMERA_TILT_DEG) -> str:
    a = ARM_OFFSET_M
    arm_z = 0.0  # base_link origin sits at the arm/bottom-plate plane
    top_plate_z = arm_z + STACK_HEIGHT_M
    spawn_z = arm_z + 0.05

    # Same rotor index/turning-direction convention as pavo_femto_gen.py
    # and PX4's own gz_x500 (0,1 one diagonal pair, 2,3 the other).
    rotor_positions = [
        (0, a, -a, "ccw"),
        (1, -a, a, "ccw"),
        (2, a, a, "cw"),
        (3, -a, -a, "cw"),
    ]

    arm_visuals = "".join(_arm_visual(f"arm{i}", cx, cy, arm_z) for i, cx, cy, _ in rotor_positions)
    rotor_links = "".join(_rotor_link(i, cx, cy, arm_z, td) for i, cx, cy, td in rotor_positions)
    motor_plugins = "".join(_motor_plugin(i, td) for i, _, _, td in rotor_positions)

    standoff_len = STACK_HEIGHT_M - PLATE_SIZE_M[2]
    standoff_offsets = [(0.024, 0.024), (0.024, -0.024), (-0.024, 0.024), (-0.024, -0.024)]
    standoffs = "".join(f"""
      <visual name="standoff_{i}">
        <pose>{_pose(dx, dy, arm_z + PLATE_SIZE_M[2] + standoff_len / 2)}</pose>
        <geometry>
          <cylinder><radius>{STANDOFF_RADIUS_M:.5f}</radius><length>{standoff_len:.5f}</length></cylinder>
        </geometry>
        <material><ambient>0.6 0.6 0.6 1</ambient><diffuse>0.7 0.7 0.7 1</diffuse></material>
      </visual>""" for i, (dx, dy) in enumerate(standoff_offsets))

    camera_x = PLATE_SIZE_M[0] / 2.0 + CAMERA_POD_SIZE_M[0] / 2.0 + 0.004
    camera_z = top_plate_z + CAMERA_POD_SIZE_M[2] / 2.0
    camera_pitch = -math.radians(camera_tilt_deg)

    antenna_x = -(PLATE_SIZE_M[0] / 2.0)
    antenna_z = top_plate_z + ANTENNA_LENGTH_M / 2.0
    antenna_pitch = math.radians(25.0)

    # Base-link inertia: flat-disc approximation over the overall
    # arm-span footprint and stack height -- engineering estimate.
    footprint_r = a * ARM_LENGTH_MARGIN
    stack_h = STACK_HEIGHT_M
    izz = BASE_MASS_KG * footprint_r ** 2 / 2.0
    ixx_iyy = BASE_MASS_KG * (3 * footprint_r ** 2 + stack_h ** 2) / 12.0

    return f"""<?xml version="1.0" encoding="UTF-8"?>
<sdf version='1.9'>
  <model name='fpv5'>
    <pose>0 0 {spawn_z:.5f} 0 0 0</pose>
    <self_collide>false</self_collide>
    <static>false</static>
    <link name="base_link">
      <inertial>
        <mass>{BASE_MASS_KG:.6f}</mass>
        <inertia>
          <ixx>{ixx_iyy:.3e}</ixx>
          <ixy>0</ixy>
          <ixz>0</ixz>
          <iyy>{ixx_iyy:.3e}</iyy>
          <iyz>0</iyz>
          <izz>{izz:.3e}</izz>
        </inertia>
      </inertial>
      <gravity>true</gravity>
      <velocity_decay/>
      {arm_visuals}
      {standoffs}
      <visual name="bottom_plate">
        <pose>{_pose(0, 0, arm_z + PLATE_SIZE_M[2] / 2)}</pose>
        <geometry>
          <box><size>{PLATE_SIZE_M[0]:.5f} {PLATE_SIZE_M[1]:.5f} {PLATE_SIZE_M[2]:.5f}</size></box>
        </geometry>
        <material><ambient>0.02 0.02 0.02 1</ambient><diffuse>0.04 0.04 0.04 1</diffuse></material>
      </visual>
      <visual name="top_plate">
        <pose>{_pose(0, 0, top_plate_z)}</pose>
        <geometry>
          <box><size>{PLATE_SIZE_M[0]:.5f} {PLATE_SIZE_M[1]:.5f} {PLATE_SIZE_M[2]:.5f}</size></box>
        </geometry>
        <material><ambient>0.02 0.02 0.02 1</ambient><diffuse>0.04 0.04 0.04 1</diffuse></material>
      </visual>
      <visual name="camera_pod">
        <pose>{_pose(camera_x, 0, camera_z, 0, camera_pitch, 0)}</pose>
        <geometry>
          <box><size>{CAMERA_POD_SIZE_M[0]:.5f} {CAMERA_POD_SIZE_M[1]:.5f} {CAMERA_POD_SIZE_M[2]:.5f}</size></box>
        </geometry>
        <material><ambient>0.02 0.02 0.02 1</ambient><diffuse>0.02 0.02 0.02 1</diffuse></material>
      </visual>
      <visual name="vtx_antenna">
        <pose>{_pose(antenna_x, 0, antenna_z, 0, antenna_pitch, 0)}</pose>
        <geometry>
          <cylinder><radius>{ANTENNA_RADIUS_M:.5f}</radius><length>{ANTENNA_LENGTH_M:.5f}</length></cylinder>
        </geometry>
        <material><ambient>0.05 0.05 0.05 1</ambient><diffuse>0.1 0.1 0.1 1</diffuse></material>
      </visual>
      <collision name="stack_collision">
        <pose>{_pose(0, 0, (arm_z + top_plate_z) / 2)}</pose>
        <geometry>
          <box><size>{PLATE_SIZE_M[0]:.5f} {PLATE_SIZE_M[1]:.5f} {STACK_HEIGHT_M:.5f}</size></box>
        </geometry>
        <surface>
          <contact><ode><min_depth>0.001</min_depth><max_vel>0</max_vel></ode></contact>
          <friction><ode/></friction>
        </surface>
      </collision>
      <sensor name="air_pressure_sensor" type="air_pressure">
        <always_on>1</always_on>
        <update_rate>50</update_rate>
        <air_pressure><pressure><noise type="gaussian"><mean>0</mean><stddev>0.01</stddev></noise></pressure></air_pressure>
      </sensor>
      <sensor name="imu_sensor" type="imu">
        <always_on>1</always_on>
        <update_rate>250</update_rate>
        <imu>
          <angular_velocity>
            <x><noise type="gaussian"><mean>0</mean><stddev>0.00018665</stddev><dynamic_bias_stddev>3.8785e-05</dynamic_bias_stddev><dynamic_bias_correlation_time>1000</dynamic_bias_correlation_time></noise></x>
            <y><noise type="gaussian"><mean>0</mean><stddev>0.00018665</stddev><dynamic_bias_stddev>3.8785e-05</dynamic_bias_stddev><dynamic_bias_correlation_time>1000</dynamic_bias_correlation_time></noise></y>
            <z><noise type="gaussian"><mean>0</mean><stddev>0.00018665</stddev><dynamic_bias_stddev>3.8785e-05</dynamic_bias_stddev><dynamic_bias_correlation_time>1000</dynamic_bias_correlation_time></noise></z>
          </angular_velocity>
          <linear_acceleration>
            <x><noise type="gaussian"><mean>0</mean><stddev>0.00186</stddev><dynamic_bias_stddev>0.006</dynamic_bias_stddev><dynamic_bias_correlation_time>300</dynamic_bias_correlation_time></noise></x>
            <y><noise type="gaussian"><mean>0</mean><stddev>0.00186</stddev><dynamic_bias_stddev>0.006</dynamic_bias_stddev><dynamic_bias_correlation_time>300</dynamic_bias_correlation_time></noise></y>
            <z><noise type="gaussian"><mean>0</mean><stddev>0.00186</stddev><dynamic_bias_stddev>0.006</dynamic_bias_stddev><dynamic_bias_correlation_time>300</dynamic_bias_correlation_time></noise></z>
          </linear_acceleration>
        </imu>
      </sensor>
      <sensor name="navsat_sensor" type="navsat">
        <always_on>1</always_on>
        <update_rate>30</update_rate>
      </sensor>
      <sensor name="camera" type="camera">
        <pose>{_pose(camera_x, 0, camera_z, 0, camera_pitch, 0)}</pose>
        <camera>
          <horizontal_fov>{CAMERA_HFOV_RAD:.5f}</horizontal_fov>
          <image><width>{CAMERA_WIDTH}</width><height>{CAMERA_HEIGHT}</height></image>
          <clip><near>0.05</near><far>100</far></clip>
        </camera>
        <always_on>1</always_on>
        <update_rate>{CAMERA_FPS}</update_rate>
        <visualize>true</visualize>
        <topic>camera</topic>
      </sensor>
      <sensor name="depth_camera" type="depth_camera">
        <pose>{_pose(camera_x, 0, camera_z, 0, camera_pitch, 0)}</pose>
        <camera>
          <horizontal_fov>{DEPTH_HFOV_RAD:.5f}</horizontal_fov>
          <image><width>{CAMERA_WIDTH}</width><height>{CAMERA_HEIGHT}</height><format>R_FLOAT32</format></image>
          <clip><near>0.1</near><far>{DEPTH_MAX_RANGE_M:.1f}</far></clip>
        </camera>
        <always_on>1</always_on>
        <update_rate>{CAMERA_FPS}</update_rate>
        <visualize>false</visualize>
        <topic>depth_camera</topic>
      </sensor>
      <!-- Real semantic segmentation, for SACR's segmentation-mask ground
           truth (env.ros.seg_topic -> ros_bridge_node.py's _on_seg). Class
           ids are assigned per-model/per-visual via the Label plugin in
           world_gen.py's to_sdf(), matching star_nav/envs/mock_env.py's
           CLASS_SKY=0/CLASS_GROUND=1/CLASS_TRUNK=2/CLASS_CANOPY=3/
           CLASS_ACTOR=4 scheme (unlabeled background, e.g. sky, defaults
           to 0). Publishes <topic>/labels_map (mono8 class-id image, what
           ros_bridge_node.py expects) and <topic>/colored_map. -->
      <sensor name="segmentation_camera" type="segmentation">
        <pose>{_pose(camera_x, 0, camera_z, 0, camera_pitch, 0)}</pose>
        <camera>
          <segmentation_type>semantic</segmentation_type>
          <horizontal_fov>{CAMERA_HFOV_RAD:.5f}</horizontal_fov>
          <image><width>{CAMERA_WIDTH}</width><height>{CAMERA_HEIGHT}</height></image>
          <clip><near>0.05</near><far>100</far></clip>
        </camera>
        <always_on>1</always_on>
        <update_rate>{CAMERA_FPS}</update_rate>
        <visualize>false</visualize>
        <topic>semantic_segmentation</topic>
      </sensor>
    </link>
    {rotor_links}
    {motor_plugins}
    <!-- Ground-truth pose for GazeboROSEnv/ros_gz_bridge's gt_odom_topic
         (env.ros.gt_odom_topic = /model/fpv5_0/odometry by default).
         Without this, nothing in Gazebo ever publishes that gz topic
         at all; ros_gz_bridge still advertises the ROS 2 side, but
         silently forwards zero messages (found the hard way:
         GazeboROSEnv.reset() hangs in wait_until_ready() with no error,
         waiting on a topic with a registered bridge but no actual
         source). -->
    <plugin filename="gz-sim-odometry-publisher-system" name="gz::sim::systems::OdometryPublisher">
      <odom_frame>world</odom_frame>
      <robot_base_frame>base_link</robot_base_frame>
      <odom_publish_frequency>30</odom_publish_frequency>
      <!-- dimensions=3 is REQUIRED: the plugin defaults to 2 (planar x/y
           only, z always 0). PX4's GZBridge feeds this odometry into the EKF
           as vehicle_visual_odometry; a 2D feed reports altitude 0 forever,
           so the vision-height fusion (EKF2_HGT_REF=Vision) is fed a constant
           0 and the altitude estimate diverges/offsets (the drone thinks it
           is metres up while sitting on the ground). 3D gives real z. -->
      <dimensions>3</dimensions>
    </plugin>
  </model>
</sdf>
"""


def build_model_config() -> str:
    return """<?xml version="1.0"?>
<model>
  <name>fpv5</name>
  <version>1.0</version>
  <sdf version="1.9">model.sdf</sdf>
  <author>
    <name>STAR-Nav project</name>
  </author>
  <description>Procedurally generated representative 5-inch FPV freestyle quad (225mm true-X wheelbase, 2207-class motors, 5.1in 3-blade props, DJI O4 Pro front camera), synthesized from Oscar Liang's "Best 5 Inch FPV Drone And Its Components" buying guide -- not one exact SKU, since that guide lists several interchangeable options per part. Built entirely from SDF primitives (no mesh assets available in this environment). See fpv5_gen.py for the full list of component choices and engineering-estimate assumptions.</description>
</model>
"""


def main(argv=None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="ros_gazebo_bridge/px4_models/fpv5",
                         help="Output model directory (will contain model.sdf and model.config)")
    parser.add_argument("--camera-tilt-deg", type=float, default=DEFAULT_CAMERA_TILT_DEG,
                         help="Camera pitch tilt in degrees, positive = nose-down. "
                              "Defaults to a typical freestyle nose-up tilt.")
    args = parser.parse_args(argv)

    os.makedirs(args.out, exist_ok=True)
    sdf_path = os.path.join(args.out, "model.sdf")
    config_path = os.path.join(args.out, "model.config")
    with open(sdf_path, "w") as f:
        f.write(build_model_sdf(camera_tilt_deg=args.camera_tilt_deg))
    with open(config_path, "w") as f:
        f.write(build_model_config())
    print(f"Wrote {sdf_path} and {config_path}")


if __name__ == "__main__":
    main()
