"""Brings up the ROS 2 side of the Gazebo+MAVLink backend: ros_gz_bridge
topic relays (camera/depth/odometry) and MAVROS (MAVLink<->ROS2).

This launch file does NOT start Gazebo or PX4 SITL themselves -- those
come from PX4-Autopilot's own build system, which this repository cannot
bundle. The expected sequence (see README.md for the full walkthrough):

    # Terminal 1: PX4 SITL + Gazebo, loading a world generated by world_gen.py
    cd PX4-Autopilot
    PX4_GZ_WORLD=<path-to>/scenario_a.sdf PX4_SIM_MODEL=gz_x500_depth \\
        make px4_sitl gz_x500_depth

    # Terminal 2: this launch file (MAVROS + ros_gz_bridge)
    ros2 launch ros_gazebo_bridge corridor_sim.launch.py

    # Terminal 3: STAR-Nav training/eval with env.name: gazebo_ros
    python scripts/run_train_all.py --config configs/default.yaml
"""
from __future__ import annotations

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description() -> LaunchDescription:
    fcu_url = LaunchConfiguration("fcu_url")
    vehicle_model = LaunchConfiguration("vehicle_model")
    rgb_topic = LaunchConfiguration("rgb_topic")
    depth_topic = LaunchConfiguration("depth_topic")
    seg_topic = LaunchConfiguration("seg_topic")
    gt_odom_topic = LaunchConfiguration("gt_odom_topic")

    return LaunchDescription([
        DeclareLaunchArgument("fcu_url", default_value="udp://:14540@127.0.0.1:14557",
                               description="MAVLink endpoint MAVROS connects to (PX4 SITL's default SITL port)"),
        DeclareLaunchArgument("vehicle_model", default_value="x500_depth",
                               description="PX4 gz vehicle model name, used to derive default gz topic names"),
        # These must match the vehicle model's gz camera-sensor <topic>
        # exactly -- ros_gz_bridge maps the gz topic to the same-named ROS
        # topic. Our models (fpv5/pavo_femto) and PX4's stock OakD camera
        # publish `/camera` and `/depth_camera` (NOT `/camera/image` etc.);
        # an earlier `/camera/image` default silently produced a ROS topic
        # with no data (the bridge advertised it but had no matching gz
        # source to forward).
        DeclareLaunchArgument("rgb_topic", default_value="/camera",
                               description="gz+ROS 2 topic the RGB camera publishes on (must match env.ros.rgb_topic)"),
        DeclareLaunchArgument("depth_topic", default_value="/depth_camera",
                               description="gz+ROS 2 topic the depth camera publishes on (must match env.ros.depth_topic)"),
        # The segmentation sensor's gz <topic> is `semantic_segmentation`, so
        # gz-sensors publishes the class-id image on `.../labels_map`
        # (mono8) and a colour visualization on `.../colored_map`. Only the
        # labels_map is bridged/consumed (ros_bridge_node.py._on_seg). NOTE:
        # only fpv5/pavo_femto carry the segmentation camera -- PX4's stock
        # x500_depth does not, so this ROS topic will have no data if you
        # launch the stock model (same "advertised but empty" behavior as
        # the camera topics on a mismatched model).
        DeclareLaunchArgument("seg_topic", default_value="/semantic_segmentation/labels_map",
                               description="gz+ROS 2 topic the segmentation camera's label map publishes on "
                                            "(must match env.ros.seg_topic; fpv5/pavo_femto only)"),
        DeclareLaunchArgument("gt_odom_topic", default_value="/model/x500_depth_0/odometry",
                               description="ROS 2 topic the vehicle's ground-truth Gazebo odometry is bridged to "
                                            "(must match env.ros.gt_odom_topic)"),

        # MAVROS: MAVLink (PX4 SITL) <-> ROS 2 topics/services.
        Node(
            package="mavros",
            executable="mavros_node",
            name="mavros",
            output="screen",
            parameters=[{
                "fcu_url": fcu_url,
                "target_system_id": 1,
                "target_component_id": 1,
                # The companion_process_status plugin crashes mavros_node on
                # this ros-humble-mavros build (rclcpp::exceptions::RCLError
                # "invalid allocator" creating a second subscription on
                # mavros/status with an incompatible type -- looks like an
                # upstream plugin bug). Not needed for this bridge (it's for
                # reporting companion-computer health back to the FCU).
                "plugin_denylist": ["companion_process_status"],
            }],
        ),

        # ros_gz_bridge: relays the vehicle's Gazebo camera/depth/odometry
        # topics into ROS 2. Topic/type pairs follow the `gz_x500_depth`
        # model's default sensor plugin outputs; adjust to match whatever
        # vehicle model your PX4-Autopilot checkout actually spawns.
        Node(
            package="ros_gz_bridge",
            executable="parameter_bridge",
            name="ros_gz_bridge",
            output="screen",
            arguments=[
                [rgb_topic, "@sensor_msgs/msg/Image[gz.msgs.Image"],
                [depth_topic, "@sensor_msgs/msg/Image[gz.msgs.Image"],
                [seg_topic, "@sensor_msgs/msg/Image[gz.msgs.Image"],
                [gt_odom_topic, "@nav_msgs/msg/Odometry[gz.msgs.Odometry"],
                "/clock@rosgraph_msgs/msg/Clock[gz.msgs.Clock",
            ],
        ),
    ])
