#!/usr/bin/env bash
# Starts PX4 SITL + Gazebo, loading the world at $PX4_GZ_WORLD (a .sdf file
# path, mounted in via the `worlds/` volume in docker-compose.yml). Headless
# by default -- set HEADLESS=0 to open the Gazebo GUI (requires X11/WSLg
# forwarding).
#
# PX4's own PX4_GZ_WORLD env var is a bare world NAME (no path/extension) --
# it looks the file up at Tools/simulation/gz/worlds/<name>.sdf (see
# build/px4_sitl_default/rootfs/gz_env.sh's PX4_GZ_WORLDS). So this script
# accepts a full .sdf path (matching world_gen.py's output) and copies it
# into that expected directory under its base name before translating
# PX4_GZ_WORLD to just the name.
set -euo pipefail

: "${PX4_GZ_WORLD:?Set PX4_GZ_WORLD to the .sdf file generated by world_gen.py}"
: "${HEADLESS:=1}"

WORLD_NAME="$(basename "$PX4_GZ_WORLD" .sdf)"
cd /opt/PX4-Autopilot
mkdir -p Tools/simulation/gz/worlds
cp "$PX4_GZ_WORLD" "Tools/simulation/gz/worlds/${WORLD_NAME}.sdf"

# gz_env.sh sets PX4_GZ_MODELS/PX4_GZ_WORLDS/GZ_SIM_RESOURCE_PATH to PX4's
# already-cloned Tools/simulation/gz submodule -- our world is self
# contained (no external model:// includes) but the vehicle model
# (x500_depth) itself is resolved from PX4_GZ_MODELS, so this must be set
# before gz sim starts. (gz_env.sh appends onto an existing
# GZ_SIM_RESOURCE_PATH without guarding for it being unset first.)
: "${GZ_SIM_RESOURCE_PATH:=}"
# shellcheck source=/dev/null
source build/px4_sitl_default/rootfs/gz_env.sh

# PX4 does not reliably auto-launch `gz sim` itself (observed empirically:
# sometimes it does, sometimes GZBridge just times out waiting for a
# server that never starts) -- launch it explicitly and deterministically
# instead of depending on that. `-s` = server only (no GUI) for HEADLESS=1.
GZ_ARGS="-r"
if [ "$HEADLESS" = "1" ]; then
    GZ_ARGS="$GZ_ARGS -s"
fi
gz sim $GZ_ARGS "Tools/simulation/gz/worlds/${WORLD_NAME}.sdf" &
GZ_PID=$!
trap 'kill "$GZ_PID" 2>/dev/null || true' EXIT

export PX4_SIM_MODEL="${PX4_SIM_MODEL:-gz_x500_depth}"
export PX4_GZ_WORLD="$WORLD_NAME"
# Without this, GZBridge gives up after a single 1-second connection
# attempt -- gz sim loading a freshly generated world (ours, not one of
# PX4's small prebuilt ones) can easily take longer than that. With it,
# GZBridge retries every 2s until Gazebo responds instead of erroring out.
export PX4_GZ_STANDALONE=1

# Without a real TTY, PX4's pxh> console spams a prompt-redraw escape
# sequence forever once the startup script finishes (cosmetic, but floods
# `docker logs`). Redirecting stdin from /dev/null gives it immediate EOF,
# which it treats as "try reading again" with no backoff -- a tight busy
# loop, worse than the redraw spam. Feeding it a pipe that stays open but
# never produces data (nothing written, never closed) makes it just block
# waiting for input instead.
#
# The make target must be "gz_<model>" -- PX4_SIM_MODEL alone does NOT
# select which model actually launches here; a literal hardcoded target
# (e.g. always "gz_x500_depth") would silently ignore PX4_SIM_MODEL for
# any other model (found while adding the pavo_femto model: setting
# PX4_SIM_MODEL=pavo_femto had no effect until this was made dynamic).
make px4_sitl "gz_${PX4_SIM_MODEL}" < <(sleep infinity)
